local_http_port= "8080"
local_docker_port= "2375"

# SSH Hop Configs
[[ssh_hops]]
order=1
user="thinpark"
host="106.14.195.98"
port=22
authType="privateKeyWithPassphrase"
privateKeyPath=".secrets/id_ed25519_ssh"
passphrase="maancoffee"
alias="Park跳板"
timeoutSec=10

[[ssh_hops]]
order=2
user="wcladmin"
host="10.153.8.4"
port=22
authType="privateKeyWithPassphrase"
privateKeyPath=".secrets/id_ed25519_ssh"
passphrase="maancoffee"
alias="服务跳板"
timeoutSec=5


[[ssh_hops]]
order=3
user="wcladmin"
host="10.153.33.7"
port=22
authType="privateKeyWithPassphrase"
privateKeyPath=".secrets/id_ed25519_ssh"
passphrase="maancoffee"
alias="内网跳板"
timeoutSec=5

[[services]]
alias="Payments V3"
host="payments-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="paymentsv3"
