local_http_port= "8080"
local_docker_port= "2375"

# SSH Hop Configs
[[ssh_hops]]
order=1
user="thinpark"
host="106.14.195.98"
port=22
authType="privateKeyWithPassphrase"
privateKeyPath=".secrets/id_ed25519"
passphrase="maancoffee"
alias="Park跳板"
timeoutSec=10

[[ssh_hops]]
order=2
user="wcladmin"
host="10.153.8.4"
port=22
authType="privateKeyWithPassphrase"
privateKeyPath=".secrets/id_ed25519"
passphrase="maancoffee"
alias="服务跳板"
timeoutSec=5


[[ssh_hops]]
order=3
user="wcladmin"
host="10.153.33.7"
port=22
authType="privateKeyWithPassphrase"
privateKeyPath=".secrets/id_ed25519"
passphrase="maancoffee"
alias="内网跳板"
timeoutSec=5



[[services]]
alias="Adobe Proxy"
host="adobe-proxy.qa.service.alihhc.hilton.com"
port="80"
subdomain="adobe-proxy"

[[services]]
alias="Akamai Assets"
host="akamai-assets.qa.service.alihhc.hilton.com"
port="80"
subdomain="akamai-assets"

[[services]]
alias="App Middleware"
host="app-middleware-alb.qa.service.alihhc.hilton.com"
port="80"
subdomain="app-middleware"

[[services]]
alias="CN Analytics"
host="cn-analytics.qa.service.alihhc.hilton.com"
port="80"
subdomain="cn-analytics"

[[services]]
alias="Apple Wallet"
host="cn-apple-wallet.qa.service.alihhc.hilton.com"
port="80"
subdomain="apple-wallet"


[[services]]
alias="Auth"
host="cn-auth.qa.service.alihhc.hilton.com"
port="80"
subdomain="auth"

[[services]]
alias="Auth H5"
host="cn-auth-h5.qa.service.alihhc.hilton.com"
port="80"
subdomain="auth-h5"

[[services]]
alias="Card Tokens"
host="cn-card-tokens.qa.service.alihhc.hilton.com"
port="80"
subdomain="card-tokens"

[[services]]
alias="Didi"
host="cn-didi.qa.service.alihhc.hilton.com"
port="80"
subdomain="didi"

[[services]]
alias="DK Edge"
host="cn-dk-edge.qa.service.alihhc.hilton.com"
port="80"
subdomain="dk-edge"

[[services]]
alias="E-fapiao GQL"
host="cn-e-fapiao-gql.qa.service.alihhc.hilton.com"
port="80"
subdomain="e-fapiao-gql"

[[services]]
alias="Federation Gateway"
host="cn-federation-gateway.qa.service.alihhc.hilton.com"
port="80"
subdomain="federation-gateway"

[[services]]
alias="Guests"
host="cn-guests.qa.service.alihhc.hilton.com"
port="80"
subdomain="guests"

[[services]]
alias="Lookups GQL"
host="cn-lookups-gql.qa.service.alihhc.hilton.com"
port="80"
subdomain="lookups-gql"

[[services]]
alias="Notifications"
host="cn-notifications.qa.service.alihhc.hilton.com"
port="80"
subdomain="notifications"

[[services]]
alias="Shortlink"
host="cn-shortlink.qa.service.alihhc.hilton.com"
port="80"
subdomain="shortlink"

[[services]]
alias="SMS"
host="cn-sms.qa.service.alihhc.hilton.com"
port="80"
subdomain="sms"

[[services]]
alias="Translations"
host="cn-translations.qa.service.alihhc.hilton.com"
port="80"
subdomain="translations"

[[services]]
alias="Control Panel UI"
host="control-panel.qa.service.alihhc.hilton.com"
port="80"
subdomain="control-panel"

[[services]]
alias="Control Panel"
host="control-panel-api.qa.service.alihhc.hilton.com"
port="80"
subdomain="control-panel-api"

[[services]]
alias="DK Share H5"
host="dk-share-h5.qa.service.alihhc.hilton.com"
port="80"
subdomain="dk-share-h5"

[[services]]
alias="Douyin Transition"
host="douyin-transition.qa.service.alihhc.hilton.com"
port="80"
subdomain="douyin-transition"

[[services]]
alias="DX Auth"
host="dx-auth-api.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-auth-api"

[[services]]
alias="DX China Core ALB"
host="dx-china-core-alb.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-china-core-alb"

[[services]]
alias="DX China Core IALB"
host="dx-china-core-internal-alb.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-china-core-internal-alb"

[[services]]
alias="DX Feature Toggles"
host="dx-feature-toggles-api.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-feature-toggles-api"

[[services]]
alias="DX Guests V2"
host="dx-guests-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-guests-v2"

[[services]]
alias="DX Hotels V2"
host="dx-hotels-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-hotels-v2"

[[services]]
alias="DX Lookups V2"
host="dx-lookups-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-lookups-v2"

[[services]]
alias="DX Offers V2"
host="dx-offers-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-offers-v2"

[[services]]
alias="DX Reservations V2"
host="dx-reservations-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-reservations-v2"

[[services]]
alias="DX Shop V2"
host="dx-shop-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-shop-v2"

[[services]]
alias="DX Stays V2"
host="dx-stays-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="dx-stays-v2"

[[services]]
alias="Extcust Proxy"
host="extcust-proxy.qa.service.alihhc.hilton.com"
port="80"
subdomain="extcust-proxy"

[[services]]
alias="Hilton Message API"
host="hilton-message-api.qa.service.alihhc.hilton.com"
port="80"
subdomain="hilton-message-api"

[[services]]
alias="Hilton OTA"
host="hilton-ota.qa.service.alihhc.hilton.com"
port="80"
subdomain="hilton-ota"

[[services]]
alias="Hilton Reports"
host="hilton-reports.qa.service.alihhc.hilton.com"
port="80"
subdomain="hilton-reports"

[[services]]
alias="Hilton Wechat"
host="hilton-wechat.qa.service.alihhc.hilton.com"
port="80"
subdomain="hilton-wechat"

[[services]]
alias="Hilton Wechat DL"
host="hilton-wechat-deeplink.qa.service.alihhc.hilton.com"
port="80"
subdomain="hilton-wechat-deeplink"

[[services]]
alias="HMS Proxy ALB"
host="hms-proxy-alb.qa.service.alihhc.hilton.com"
port="80"
subdomain="hms-proxy-alb"

[[services]]
alias="Keycloak"
host="keycloak.qa.service.alihhc.hilton.com"
port="80"
subdomain="keycloak"

[[services]]
alias="MLA"
host="mla.qa.service.alihhc.hilton.com"
port="80"
subdomain="mla"

[[services]]
alias="MLA Processor"
host="mla-processor.qa.service.alihhc.hilton.com"
port="80"
subdomain="mla-processor"

[[services]]
alias="MLA Sync"
host="mla-sync.qa.service.alihhc.hilton.com"
port="80"
subdomain="mla-sync"

[[services]]
alias="MP Assets"
host="mp-assets.qa.service.alihhc.hilton.com"
port="80"
subdomain="mp-assets"

[[services]]
alias="Payments V3"
host="payments-v2.qa.service.alihhc.hilton.com"
port="80"
subdomain="paymentsv3"

[[services]]
alias="Pre Translate"
host="pre-translate.qa.service.alihhc.hilton.com"
port="80"
subdomain="pretranslate"

[[services]]
alias="Push Notification"
host="push-notification.qa.service.alihhc.hilton.com"
port="80"
subdomain="push-notification"

[[services]]
alias="Social Login UI"
host="social-login-ui.qa.service.alihhc.hilton.com"
port="80"
subdomain="social-login-ui"

[[services]]
alias="Starbucks"
host="starbucks.qa.service.alihhc.hilton.com"
port="80"
subdomain="starbucks"

[[services]]
alias="TokenizeJS"
host="tokenizejs.qa.service.alihhc.hilton.com"
port="80"
subdomain="tokenizejs"

[[services]]
alias="WX Share"
host="wx-share.qa.service.alihhc.hilton.com"
port="80"
subdomain="wx-share"